---
- include: deps.yml
- name: Copy multiverse-db
  copy:
    src=multiverse-db
    dest=/usr/local/src
    mode=u=rwx,g=rwx,o=rx
- name: Running npm install
  command: npm install
    chdir=/usr/local/src/multiverse-db
    creates=/usr/local/src/multiverse-db/node_modules
# - name: Running Setup Database
#   command: npm run setup -- --yes
#     chdir=/usr/local/src/multiverse-db